version: '3.1'
services:
  db:
    image: aidbox/db:13.0.0
    container_name: zendb
    ports:
      - "5451:5432"
    volumes:
      - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "postgres" 
      POSTGRES_PASSWORD: "postgres" 
      POSTGRES_DB:       "mybox"
